
CREATE TABLE states (
    state_id BIGSERIAL PRIMARY KEY,
    state_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    status VARCHAR(20) DEFAULT 'ACTIVE'
);



